### ISSUE TITLE
Indentation issues on Spacemacs

### ISSUE THREAD

**Issue by jaysoifer** [AdamNiederer/vue-mode#43]
Hi,

With your help and support I have been finally able to make **vue-mode** work on Spacemacs! Yey!

So, autocomplete is working on CSS:

<img width="510" alt="screen shot 2017-08-12 at 11 05 00" src="https://user-images.githubusercontent.com/8316698/29239120-49f0a6e0-7f4e-11e7-835e-3735148551b8.png">

But, as you can see, for some reason when going into a new line within the **CSS/SaSS** style, the cursor is pushed many columns to the right.

Mind you, I'm using *Evil* Mode, not sure it makes any difference.

Any ideas or pointers on how to fix this?

**Comment by AdamNiederer** [comment]
Hm, it looks like your modeline says you're in `css-mode`, but you're using SASS syntax. Could you send me a full template file which demonstrates this issue?

**Comment by jaysoifer** [comment]
Sure:
https://gist.github.com/jaysoifer/c7fcc03c0faf3789da62a67cb576a3ef

Didn't include it in full here because it's too big 🤓

**Comment by AdamNiederer** [comment]
Hm, I've crafted a patch to make `ssass-mode` more amenable to autocompletion (I actually couldn't get it working at all on master), but I can't reproduce the issue you're experiencing. Are you using the prepackaged [ssass mode](https://github.com/AdamNiederer/ssass-mode), or [sass mode](https://github.com/nex3/sass-mode)?

**Comment by jaysoifer** [comment]
😳 
How can I tell?

**Comment by AdamNiederer** [comment]
```elisp
(progn (require 'vue-mode)
       (plist-get
        (car (remove-if-not (lambda (e) (equal 'sass (plist-get e :name))) vue-modes))
        :mode))
```
This will print the name of your sass submode. Move your point to the end of the last paren and press `C-x C-e` to evaluate it.

**Comment by jaysoifer** [comment]
<img width="173" alt="screen shot 2017-08-16 at 23 03 13" src="https://user-images.githubusercontent.com/8316698/29382981-20239976-82d7-11e7-99bb-3739f880db3f.png">

**Comment by colorwin** [comment]
I did't have this problem, but I have a other indent issue in speacmacs.
When I pess 'SPC j =' for 'spacemacs/indent-region-or-buffer' in 'vue[vue-Ssass]' mode, it will make indent  mess.

A simple before 'SPC j =':
```css
<style lang="sass">
 @import "~sass/reset.scss";
 @import "~sass/base.scss";
 @import "~sass/gray.scss";
 @import "~assets/css/iconfont.css";

.fillData {
    h5 {
        display: flex;
        padding: 0 px2rem2(15);
        font-weight: normal;
        height: px2rem2(44);
        line-height: px2rem2(44);
        color: #888;
        @include big-fs();
        &.remove-title {
            justify-content: space-between;
        }
    }
}
```

If I just select inner css,  'SPC j =':
```css
@import "~sass/base.scss";
  @import "~sass/reset.scss";
    @import "~sass/gray.scss";
    @import "~assets/css/iconfont.css";

    .fillData {
        h5 {
            display: flex;
            padding: 0 px2rem2(15);
            font-weight: normal;
            height: px2rem2(44);
            line-height: px2rem2(44);
            color: #888;
            @include big-fs();
            &.remove-title {
                justify-content: space-between;
            }
        }
    }
```

If I select outer `<style></style>' tag, 'SPC j =':
```css
<style lang="sass">
  @import "~sass/reset.scss";
@import "~sass/base.scss";
@import "~sass/gray.scss";
@import "~assets/css/iconfont.css";

.fillData {
    h5 {
        display: flex;
        padding: 0 px2rem2(15);
        font-weight: normal;
        height: px2rem2(44);
        line-height: px2rem2(44);
        color: #888;
        @include big-fs();
        &.remove-title {
            justify-content: space-between;
        }
    }
}
  </style>
```
